server:
  port: 1111

spring:
  application:
    name: xdd-consumer
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1110/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2


#feign:
#  hystrix:
#    enabled: true